name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install package + test deps
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]" # CPU-only test run, use [dev,cuda] if you want to use NVIDIA GPUs
    - name: Run tests
      run: |
        pytest -q
